### ISSUE TITLE
部署过程中数据库导入以及appid secret 的问题

### ISSUE THREAD

**Issue by EGBAR** [tencentyun/weapp-session-server#1]
1 数据库导入 db.sql 的过程中需要创建或者使用的数据库名称是什么，是叫cAuth吗？ 安装步骤中没有写清楚。

2 appid 是微信小程序的App Id，App secret 需要在网页上生成，每次生成的是不一样的，是否所有的设置中的secret 都需要应用最新的那个版本？

-------------------------------------------------------
sorry, 没注意到db.ini 文件中可以配置，已解决

**Comment by HNJKSDH** [comment]
感谢反馈，第一个问题，是cAuth,我去修改一下github
第二个问题 是的，最新版本。



在 2017-01-04 01:03:24，"EGBAR" <notifications@github.com> 写道：


1 数据库导入 db.sql 的过程中需要创建或者使用的数据库名称是什么，是叫cAuth吗？ 安装步骤中没有写清楚。

2 appid 是微信小程序的App Id，App secret 需要在网页上生成，每次生成的是不一样的，是否所有的设置中的secret 都需要应用最新的那个版本？
